version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    # command:
    #   - "--configFile=/traefik.yml"
      # - "--log.level=DEBUG"
      # - "--log.filePath=/path/to/traefik.log"
      # - "--accesslog=true"
      # - "--api.insecure=true"
      # - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.web.address=:80"
    ports:
      - "6500:80"
      - "6501:8080"
    volumes:
      # NOTE: must be mounted to directory for live reload to work
      - "./config/routes/:/traefik/:rw"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"