http:
  # add the prefix for legacy
  middlewares:
    addLegacy:
      addPrefix:
        prefix: "/npm/pkg"
    testHeader:
      headers:
        customRequestHeaders:
          Host: "alt-registry-service.xlts.dev"

  # create a route for both current and legacy
  routers:
    registry-local:
      rule: Host(`registry.localhost`) # && (PathPrefix(`/npm/pkg/@neverendingsupport`) || PathPrefix(`/npm/pkg/@xlts.dev`))
      middlewares:
        - testHeader
      service: splitter-svc
      # service: registry-local-svc
    registry-prod:
      rule: Host(`registry.system.herodevs.io`) && (PathPrefix(`/npm/pkg/@neverendingsupport`) || PathPrefix(`/npm/pkg/@xlts.dev`))
      service: registry-prod-svc
    legacy-local:
      rule: Host(`legacy.localhost`) && (PathPrefix(`/@neverendingsupport`) || PathPrefix(`/@xlts.dev`))
      middlewares:
        - addLegacy # add the prefix
      service: registry-local-svc
    legacy-prod:
      # rule: (Host(`xlts.system.herodevs.io`) || Host(`registry.xlts.dev`)) && (PathPrefix(`/@neverendingsupport`) || PathPrefix(`/@xlts.dev`))
      rule: (Host(`xlts.system.herodevs.io`) || Host(`registry.xlts.dev`)) # && (PathPrefix(`/@neverendingsupport`) || PathPrefix(`/@xlts.dev`))
      middlewares:
        - addLegacy # add the prefix
      service: registry-prod-svc
  services:
    splitter-svc:
      weighted:
        services:
        - name: registry-local-svc
          weight: 99
        - name: xlts-staging-svc
          weight: 1
    registry-local-svc:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:3010/"
    xlts-staging-svc:
      loadBalancer:
        passHostHeader: false
        servers:
        - url: "https://alt-registry-staging.xlts.dev/"
    registry-prod-svc:
      loadBalancer:
        passHostHeader: false
        servers:
        - url: "https://registry.nes.herodevs.com/"